config/routes.rb
Rails.application.routes.draw do
  root    'graphs#new'
  patch   'graphs/:token', to: 'graphs#update'
  get     'graphs/new',    to: 'graphs#new',    as: 'new_graph'
  post    'graphs',        to: 'graphs#create', as: 'create_graph'
  get     'graphs/:token', to: 'graphs#edit',   as: 'edit_graph'
  delete  'graphs/:token', to: 'graphs#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graph.rb
class Graph < ApplicationRecord
  validates :token, presence: true, uniqueness: true
  validates :data, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
require 'securerandom'

class GraphsController < ApplicationController
  def new
  end

  def create
    graph = Graph.new(token: SecureRandom.uuid, encrypted: false)

    if graph.save
      redirect_to edit_graph_path(graph.token)
    else
      flash[:danger] = graph.errors.full_messages.to_sentence
      redirect_to root_path
    end
  end

  def edit
    @graph = Graph.find_by(token: params[:token])
    @data = @graph.encrypted ? "#{@graph.data.to_json}" : @graph.data.as_json
  end

  def update
    graph = Graph.find_by(token: params[:token])

    respond_to do |format|
      format.json do
        if graph.update_attributes(data: params[:data], encrypted: params[:encrypted])
          render json: nil, status: 200
        else
          render json: nil, status: 400
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
  def in_edit_view?
    'graphs/edit' == "#{controller_name}/#{action_name}" 
  end
end

app/views/graphs/_load_password_prompt.html.haml
#load-password-prompt.modal{:role => "dialog"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Enter Password
      .modal-body
        %p
          Your tree is encrypted, please submit your password
        %input#password.form-control{type: 'password', placeholder: 'Password'}
        .wrong-password Wrong password!
        .cipher
      .modal-footer
        %button#load.btn.btn-primary.pull-left{:type => "button"} Load

app/views/graphs/_popup.html.haml
%span#operation
- options = [ ['Root statement', 'rootStatement'], ['Statement', 'statement'], ['Choice', 'choice'] ]
= select_tag "node-group", options_for_select(options, "statement"), {class: 'form-control'}
%textarea#node-label.form-control{placeholder: 'Type anything here...'}
%button#save-button.btn.btn-success save
%button#cancel-button.btn.btn-default cancel
= hidden_field_tag 'node-id'

app/views/graphs/_save_password_prompt.html.haml
#save-password-prompt.modal{:role => "dialog"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Enter Password
      .modal-body
        %p
          You have chosen to protect the content of your tree with password-based encryption. Please enter your password now before things become stored in our DB.

        %input#password.form-control{type: 'password', placeholder: 'Password'}
        %br
        %input#password-confirmation.form-control{type: 'password', placeholder: 'Confirm password'}
        %br
        %p
          %i Please note: Your password needs to be at least 6 characters long


        .cipher
      .modal-footer
        %button#encrypt-and-push-to-backend.btn.btn-primary.pull-left{:type => "button", disabled: true} Save
        %button.btn.btn-primary.btn-danger{"data-dismiss" => "modal", :type => "button"} Cancel

app/views/graphs/edit.html.haml
= title "NuxBuilder - Edit Graph"

#builder
  .row
    .col-xs-12.col-md-8
      #network-popUp.well.bs-component
        = render 'popup'
      #graph
        Locked by password
      #nux-messages
    .col-xs-12.hidden-md.hidden-lg
      Json:
    .col-xs-12.col-md-4
      .raw-textarea-container
        %textarea#raw-data-textarea{disabled: true}
        %button#push-to-backend-button.btn.btn-default.action-button{title: 'Save'}
          save

        %label.lock{title: 'encryption'}
          %input{type: 'checkbox', id: 'shall-encrypt', checked: @graph.encrypted}
          %i.fa.fa-lock.checked
          %i.fa.fa-unlock.unchecked

= render 'save_password_prompt'
= render 'load_password_prompt'

:javascript
  window.graphData = #{raw @data}
  window.graphToken = "#{@graph.token}"
  window.encrypted = #{@graph.encrypted}

= javascript_pack_tag 'graph'
= stylesheet_pack_tag 'src/graph'

app/views/graphs/new.html.haml
#landing-page
  .row
    .col-xs-12
      = image_tag 'nux_landing_page_img', class: 'logo'

  .row
    .col-xs-12
      #nux

  .row
    .col-xs-12
      %h1.text-center You need something like this for your website?
      %h3.text-center
        = link_to 'Create your own decision tree', create_graph_path, method: :post
        with nuxBuilder and
        = link_to 'embed it with the nux javascript library', ''

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title= yield(:title)
    = favicon_link_tag 'favicon'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          %a.navbar-brand{href: root_path}
            nux.js
            = image_tag 'nux_logo'

    .container
      = yield
    = link_to 'https://coderat.cc' do
      = image_tag 'coderat_logo', class: 'coderat-logo'